ScheduleCreator/Models/Instructor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleCreator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.InstructorPrograms = new HashSet<InstructorProgram>();
            this.InstructorReleases = new HashSet<InstructorRelease>();
            this.Sections = new HashSet<Section>();
        }
    
        public int instructor_id { get; set; }

        [DisplayName("W Number")]
        [StringLength(9)]
        [Required(ErrorMessage = "Instructor wnumber is required")]
        public string instructorWNumber { get; set; }

        [DisplayName("First Name")]
        [StringLength(50)]
        [Required(ErrorMessage = "Instructor first name is required")]
        public string instructorFirstName { get; set; }

        [DisplayName("Last Name")]
        [StringLength(50)]
        [Required(ErrorMessage = "Instructor last name is required")]
        public string instructorLastName { get; set; }

        [DisplayName("Hours Required")]
        public Nullable<decimal> hoursRequired { get; set; }

        [DisplayName("Active")]
        public string active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorProgram> InstructorPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorRelease> InstructorReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}

ScheduleCreator/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleCreator.Models;

namespace ScheduleCreator.Controllers
{
    public class SectionsController : Controller
    {
        private ScheduleCreatorEntities db = new ScheduleCreatorEntities();

        // GET: Sections
        public ActionResult Index()
        {
            var sections = db.Sections.Include(s => s.Classroom).Include(s => s.Course).Include(s => s.Instructor).Include(s => s.Semester);
            return View(sections.ToList());
        }

        // GET: Sections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: Sections/Create
        public ActionResult Create()
        {
            ViewBag.classroom_id = new SelectList(
                 from cl in db.Classrooms
                 orderby cl.buildingPrefix, cl.roomNumber
                 select new { cl.classroom_id, cl.buildingPrefix, cl.roomNumber, fullName = cl.buildingPrefix + " " + cl.roomNumber },
                 "classroom_id", "fullName");
            ViewBag.course_id = new SelectList(
                 from c in db.Courses
                 orderby c.coursePrefix, c.courseNumber
                 select new { c.course_id, c.coursePrefix, c.courseNumber, fullName = c.coursePrefix + " " + c.courseNumber },
                 "course_id", "fullName");
            ViewBag.instructor_id = new SelectList(
                 from i in db.Instructors
                 orderby i.instructorLastName, i.instructorFirstName
                 select new { i.instructor_id, i.instructorFirstName, i.instructorLastName, fullName = i.instructorLastName + ", " + i.instructorFirstName },
                 "instructor_id", "fullName");
            ViewBag.semester_id = new SelectList(
                from s in db.Semesters
                orderby s.startDate descending
                select new { s.semester_id, s.semesterType, s.semesterYear, fullName = s.semesterType + " " + s.semesterYear },
                "semester_id", "fullName");

            

            ViewBag.block = new SelectList(Section.BlockTypes.Keys.ToList());
            ViewBag.courseType = new SelectList(Section.CourseTypes.Keys.ToList());

            ViewBag.dayReCheck = new List<bool>() { false, false, false, false, false, false };

            return View();
        }

        // POST: Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "section_id,course_id,classroom_id,instructor_id,semester_id,crn,courseStartTime,courseEndTime,block,courseType,pay,sectionCapacity,creditLoad,creditOverload,comments")] Section section, List<string> dayChecks)
        {
            // Get values for rest of fields based of id
            // coursePrefix,courseNumber
            section.coursePrefix = (from c in db.Courses where c.course_id == section.course_id select c.coursePrefix).ToList().FirstOrDefault();
            section.courseNumber = (from c in db.Courses where c.course_id == section.course_id select c.courseNumber).ToList().FirstOrDefault();

            // buildingPrefix,roomNumber
            section.buildingPrefix = (from cl in db.Classrooms where cl.classroom_id == section.classroom_id select cl.buildingPrefix).ToList().FirstOrDefault();
            section.roomNumber = (from cl in db.Classrooms where cl.classroom_id == section.classroom_id select cl.roomNumber).ToList().FirstOrDefault();

            // instructorWNumber
            section.instructorWNumber = (from i in db.Instructors where i.instructor_id == section.instructor_id select i.instructorWNumber).ToList().FirstOrDefault();

            // semesterType,semesterYear
            section.semesterType = (from s in db.Semesters where s.semester_id == section.semester_id select s.semesterType).ToList().FirstOrDefault();
            section.semesterYear = (from s in db.Semesters where s.semester_id == section.semester_id select s.semesterYear).ToList().FirstOrDefault();

            // Replace selection with shortened form
            section.block = Section.BlockTypes[section.block];
            section.courseType = Section.CourseTypes[section.courseType];

            // Handle daysTaught checkboxes
            // Loop through the returned array append value to daysTaught
            if (dayChecks != null)
                dayChecks.ForEach(day => section.daysTaught += day);

            try
            {
                if (ModelState.IsValid)
                {
                    db.Sections.Add(section);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                if (e.InnerException.InnerException.Message.Contains("UNIQUE KEY constraint"))
                {
                    ModelState.AddModelError("comments", "The section has already been created");
                }
                else
                {
                    ModelState.AddModelError("comments", e.InnerException.InnerException.Message);
                }
            }

            ViewBag.classroom_id = new SelectList(
                 from cl in db.Classrooms
                 orderby cl.buildingPrefix, cl.roomNumber
                 select new { cl.classroom_id, cl.buildingPrefix, cl.roomNumber, fullName = cl.buildingPrefix + " " + cl.roomNumber },
                 "classroom_id", "fullName", section.classroom_id);
            ViewBag.course_id = new SelectList(
                 from c in db.Courses
                 orderby c.coursePrefix, c.courseNumber
                 select new { c.course_id, c.coursePrefix, c.courseNumber, fullName = c.coursePrefix + " " + c.courseNumber },
                 "course_id", "fullName", section.course_id);
            ViewBag.instructor_id = new SelectList(
                 from i in db.Instructors
                 orderby i.instructorLastName, i.instructorFirstName
                 select new { i.instructor_id, i.instructorFirstName, i.instructorLastName, fullName = i.instructorLastName + ", " + i.instructorFirstName },
                 "instructor_id", "fullName", section.instructor_id);
            ViewBag.semester_id = new SelectList(
                from s in db.Semesters
                orderby s.startDate descending
                select new { s.semester_id, s.semesterType, s.semesterYear, fullName = s.semesterType + " " + s.semesterYear },
                "semester_id", "fullName", section.semester_id);

            // Lookup key based on value. Doesn't work if there are duplicate values.
            string previousBlock = Section.BlockTypes.FirstOrDefault(x => x.Value == section.block).Key;
            string previousCourseType = Section.CourseTypes.FirstOrDefault(x => x.Value == section.courseType).Key;
            ViewBag.block = new SelectList(Section.BlockTypes.Keys.ToList(), previousBlock);
            ViewBag.courseType = new SelectList(Section.CourseTypes.Keys.ToList(), previousCourseType);

            // Set up checkboxes
            List<bool> dayReCheck = new List<bool>();
            bool checkDay;
            foreach (string day in Section.days)
            {
                checkDay = false;
                foreach (char check in section.daysTaught.ToString())
                {
                    if (check.ToString() == day)
                    {
                        checkDay = (true);
                        break;
                    }
                }
                dayReCheck.Add(checkDay);
            }
            ViewBag.dayReCheck = dayReCheck;
            return View(section);
        }

        // GET: Sections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            ViewBag.classroom_id = new SelectList(
                 from cl in db.Classrooms
                 orderby cl.buildingPrefix, cl.roomNumber
                 select new { cl.classroom_id, cl.buildingPrefix, cl.roomNumber, fullName = cl.buildingPrefix + " " + cl.roomNumber },
                 "classroom_id", "fullName", section.classroom_id);
            ViewBag.course_id = new SelectList(
                 from c in db.Courses
                 orderby c.coursePrefix, c.courseNumber
                 select new { c.course_id, c.coursePrefix, c.courseNumber, fullName = c.coursePrefix + " " + c.courseNumber },
                 "course_id", "fullName", section.course_id);
            ViewBag.instructor_id = new SelectList(
                 from i in db.Instructors
                 orderby i.instructorLastName, i.instructorFirstName
                 select new { i.instructor_id, i.instructorFirstName, i.instructorLastName, fullName = i.instructorLastName + ", " + i.instructorFirstName },
                 "instructor_id", "fullName", section.instructor_id);
            ViewBag.semester_id = new SelectList(
                from s in db.Semesters
                orderby s.startDate descending
                select new { s.semester_id, s.semesterType, s.semesterYear, fullName = s.semesterType + " " + s.semesterYear },

ScheduleCreator/Views/Instructors/Delete.cshtml
@model ScheduleCreator.Models.Instructor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.instructorWNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.instructorWNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.instructorFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.instructorFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.instructorLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.instructorLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hoursRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hoursRequired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ScheduleCreator/Views/Instructors/FinalFormat.cshtml
@model IEnumerable<ScheduleCreator.Models.Instructor>

@{
    ViewBag.Title = "Final Format";
}
<script type="text/javascript">
    function printData()
    {
        var divToPrint = document.getElementById("FinalFormat");
        newWin = window.open("");
        newWin.document.write(divToPrint.outerHTML);
        newWin.print();
        newWin.close();
    }
   
    $('button').on('click', function(){
        printData();
    } )
</script>

<h2>Final Format </h2>

<div>
    <input type="button" onclick="javascript:printData()" value="Print"/>
</div>
<br/>
<table id="FinalFormat" class="table table-hover " border="1" >
    <tr bgcolor="#778899">
        <th>
            Instructor
        </th>
        <th>
            Course
        </th>
        <th>
            CRN
        </th>
        <th colspan="2">
            Hours
        </th>
        <th>
            Days
        </th>
        <th>
            Room
        </th>
        <th>
            Max
        </th>
        <th>
            Credit Hours
        </th>
        <th>
            Campus
        </th>
        <th>
            Pay
        </th>
        <th>
            Load/Overload
        </th>
        <th>
            Hours Required
        </th>
    </tr>

    @foreach (var instructor in Model)
    {
        <tr BGCOLOR="D3D3D3">
            <td colspan="12">
                <strong> @Html.DisplayFor(modelItem => instructor.instructorLastName), @Html.DisplayFor(modelItem => instructor.instructorFirstName)</strong>
            </td>
            <td>
                @Html.DisplayFor(modelItem => instructor.hoursRequired)
            </td>
        </tr>
        foreach (var section in instructor.Sections)
        {
            <tr>
                <td>
                    @Html.ActionLink("Edit Section", "Edit", "Sections", new { @id = section.section_id }, null)
                </td>
                <td>
                    <a href="../Courses/Edit/@Html.DisplayFor(sectionItem => section.Course.course_id)">@Html.DisplayFor(sectionItem => section.coursePrefix)@Html.DisplayFor(sectionItem => section.courseNumber)</a>
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.crn)
                </td>
                <td>
                    @(section.courseStartTime.ToString())
                </td>
                <td>
                    @(section.courseEndTime.ToString())
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.daysTaught)
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.buildingPrefix)-@Html.DisplayFor(sectionItem => section.roomNumber)
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.sectionCapacity)
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.Course.defaultCredits)
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.Classroom.Building.campusPrefix)
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.pay)
                </td>
                <td>
                    @Html.DisplayFor(sectionItem => section.creditLoad) / @Html.DisplayFor(sectionItem => section.creditOverload)
                </td>
                <td></td>
            </tr>
        }
        <tr>
            @foreach(var release in instructor.InstructorReleases)
            {
                <td>Release Hours</td>
                <td colspan="12">@release.releaseDescription -- @release.totalReleaseHours Units Release</td>
            }
        </tr>

    }

</table>

ScheduleCreator/Views/Instructors/InstructorCalendar.cshtml
@model IEnumerable<ScheduleCreator.Models.Instructor>

@{
    ViewBag.Title = "Instructor Calendar";
}

@Styles.Render("~/Content/easycal.css")

@Scripts.Render("~/Scripts/underscore.min.js")
@Scripts.Render("~/Scripts/moment.min.js")
@Scripts.Render("~/Scripts/easycal.js")

<div class="container" style="vertical-align:central; margin:5px;">
    <div class="col-lg-4 col-md-5">
        <h2>@ViewBag.Title</h2>
    </div>

    <div class="col-lg-4 col-md-5 col-md-offset-2 col-lg-offset-4">
        <h4 style="text-align:center">Select Semester</h4>
        <select onChange="window.location.assign(this.value)" class="form-control" style="float:right">

            @foreach (ScheduleCreator.Models.Semester s in ViewBag.semesterList)
            {
                if (s == ViewBag.CurrentSemester)
                {
                    <option value=@Url.Action("InstructorCalendar", "Instructors", new { id = s.semester_id }) selected="selected">@s.semesterType @s.semesterYear</option>
                }
                else
                {
                    <option value=@Url.Action("InstructorCalendar", "Instructors", new { id = s.semester_id })>@s.semesterType @s.semesterYear</option>
                }
            }
        </select>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div >
            @Html.DropDownList("instructor_id", null, htmlAttributes: new { id = "cal1-nav", @class = "form-control", onclick = "showCalendar('cal', this.value)" })
        </div>
        <div class="col-lg-10" style="max-height: 400px; overflow-y: auto">

            @foreach (var Instructor in Model)
            {
                <div id="cal-@Instructor.instructor_id" class="@Instructor.instructor_id" style="width:100%; display:none;"></div>
            }
        </div>
    </div>
    <br />
    <div class="row">
        <div >
            @Html.DropDownList("instructor_id", null, htmlAttributes: new { id = "cal2-nav", @class = "form-control", onclick = "showCalendar('cal2', this.value)" })
        </div>
        <div class="col-lg-10" style="max-height: 400px; overflow-y: auto">

            @foreach (var Instructor in Model)
            {
                <div id="cal2-@Instructor.instructor_id" class="@Instructor.instructor_id" style="width:100%; display:none;"></div>
            }
        </div>
    </div>
</div>
<script>

@foreach (var Instructor in Model) {
<text>
    var temp = $('.@Instructor.instructor_id');
    var eventObjects = @Html.Raw(ViewBag.instructorEvents[@Instructor.instructor_id]);
    temp = generateCalendars(eventObjects);
    </text>
}
    showCalendar("cal", @Model.ElementAt(0).instructor_id)
    showCalendar("cal2", @Model.ElementAt(1).instructor_id)
    $("#cal2-nav").val("@Model.ElementAt(1).instructor_id")

    function generateCalendars(eventObjects){
        return temp.easycal({
            startDate: '01-01-1900', // OR 31/10/2104
            timeFormat: 'hh:mm a',
            columnDateFormat: 'ddd',
            minTime: '06:00:00',
            maxTime: '23:00:00',
            slotDuration: 30,
            timeGranularity: 15,

            dayClick: function(el, startTime) {
                //alert('Slot selected: ' + startTime);
            },

            eventClick: function(eventId) {
                window.location = "@Url.Action("Edit", "Sections")/" + eventId;
            },

            events: eventObjects,

            overlapColor: '#F00',
            overlapTextColor: '#FFF',
            overlapTitle: 'Multiple'
        });
    }

    var lastCal;
    var lastCal2;
    function showCalendar(cal, instId)
    {
        var name = cal + "-" + instId;
        if (cal == 'cal'){
            $("#" + lastCal).hide();
            lastCal = name;
        }
        else{
            $("#" + lastCal2).hide();
            lastCal2 = name;
        }
        document.getElementById(name).style.display = "block";
    }

</script>

ScheduleCreator/Views/Instructors/SectionByInstructor.cshtml
@model IEnumerable<ScheduleCreator.Models.Instructor>


@{
    ViewBag.Title = "Section By Instructor";
}

<style type="text/css">
    .row {
        margin-left: 0px;
        margin-right: 0px;
    }

    td {
        border: 1px solid #dddddd;
    }

    th {
        text-align: center;
        background-color: #f5f5f5;
        border: 1px solid #dddddd;
        font-size: 18px;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }

    tr:hover {
        background: #EEEEEE;
    }
</style>
<div>
    <br/>
    <button bgcolor="#d3d3d3" class="btn btn-lg btn-default col-md-offset-10">@Html.ActionLink("Semester Schedule", "SemesterSchedule", "Instructors", new { id=ViewBag.CurrentSemester.semester_id})</button>
</div>
<div class="container" style="vertical-align:central; margin:5px;">
    <div class="col-lg-4 col-md-5">
        <h2>@ViewBag.Title</h2>
    </div>
    
    <div class="col-lg-4 col-md-5 col-md-offset-2 col-lg-offset-4">
        <h4 style="text-align:center">Select Semester</h4>
        <select onChange="window.location.assign(this.value)" class="form-control" style="float:right">
            @foreach (ScheduleCreator.Models.Semester s in ViewBag.semesterList)
            {
                if (s == ViewBag.CurrentSemester)
                {
                    <option value=@Url.Action("SectionByInstructor", "Instructors", new { id = s.semester_id }) selected="selected">@s.semesterType @s.semesterYear</option>
                }
                else
                {
                    <option value=@Url.Action("SectionByInstructor", "Instructors", new { id = s.semester_id })>@s.semesterType @s.semesterYear</option>
                }
            }
        </select>
    </div>
</div>

<div class="panel-group">
    @foreach (var item in Model)
    {

        decimal totalHrs = 0;

        foreach (var hrs in item.Sections)
        {
            totalHrs += hrs.creditLoad != null ? (decimal)hrs.creditLoad : 0;
            totalHrs += hrs.creditOverload != null ? (decimal)hrs.creditOverload : 0;
        }


        foreach (var hrs in item.InstructorReleases)
        {
            totalHrs += (decimal)(hrs.totalReleaseHours);
        }

        if (item.Sections.Count > 0 || item.InstructorReleases.Count > 0)
        {

            <div class="panel panel-default">
                <div class="panel-heading row" style="width:100%">
                    <div class="col-lg-3 col-md-4 col-sm-12">
                        <h3 class="panel-title">
                            <a data-toggle="collapse" href="#collapse-@Html.DisplayFor(modelItem => item.instructor_id)">@Html.DisplayFor(modelItem => item.instructorLastName), @Html.DisplayFor(modelItem => item.instructorFirstName)</a>
                        </h3>
                    </div>

                    <div class="col-lg-4 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-12">
                        <h3>
                            Hours Assigned: @totalHrs / @item.hoursRequired
                        </h3>
                    </div>
                </div>
                <div id="collapse-@Html.DisplayFor(modelItem => item.instructor_id)" class="panel-collapse collapse">
                    <div class="panel-body" style="overflow:auto">

                        @if (item.Sections.Count > 0)
                        {
                            <h3>Sections</h3>
                            <table style="text-align:center; width:100%;">
                                <tr>
                                    <th>
                                    </th>
                                    <th>
                                        Course
                                    </th>
                                    <th>
                                        CRN
                                    </th>
                                    <th colspan="2">
                                        Time
                                    </th>
                                    <th>
                                        Days
                                    </th>
                                    <th>
                                        Room
                                    </th>
                                    <th>
                                        Room Capacity
                                    </th>
                                    <th>
                                        Credit Hours
                                    </th>
                                    <th>
                                        Campus
                                    </th>
                                    <th>
                                        Pay
                                    </th>
                                    <th>
                                        Load Hrs
                                    </th>
                                    <th>
                                        OverLoad Hrs
                                    </th>
                                </tr>
                                @foreach (var section in item.Sections)
                                {
                                    <tr>
                                        <td>
                                            @Html.ActionLink("Edit Section", "Edit", "Sections", new { @id = section.section_id }, null)
                                        </td>
                                        <td>
                                            <a href="../Courses/Edit/@Html.DisplayFor(sectionItem => section.Course.course_id)">@Html.DisplayFor(sectionItem => section.coursePrefix)@Html.DisplayFor(sectionItem => section.courseNumber)</a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.crn)
                                        </td>
                                        <td>
                                            @(section.courseStartTime.ToString())
                                        </td>
                                        <td>
                                            @(section.courseEndTime.ToString())
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.daysTaught)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.buildingPrefix)-@Html.DisplayFor(sectionItem => section.roomNumber)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.sectionCapacity)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.Course.defaultCredits)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.Classroom.Building.campusPrefix)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.pay)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.creditLoad)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(sectionItem => section.creditOverload)
                                        </td>
                                    </tr>
                                }
                            </table>
                        } <!--end if-->

                        @if (item.InstructorReleases.Count > 0)
                        {
                            <h3>Released Time</h3>
                            <table style="text-align:center; width:100%;">
                                <tr>
                                    <th>

                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th>
                                        Released Hours
                                    </th>
                                </tr>
                                @foreach (var release in item.InstructorReleases)
                                {
                                    <tr>
                                        <td><a>Edit</a></td>
                                        <td>
                                            @Html.DisplayFor(releaseItem => release.releaseDescription)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(releaseItem => release.totalReleaseHours)
                                        </td>
                                    </tr>
                                }
                            </table>
                        }
                    </div> <!--End Panel Body-->
                </div> <!--End Panel-->
            </div> <!--End Accordion Item-->
        }
    }
</div> <!--End Accordion-->